### ISSUE TITLE
在vercel部署的onemanager don't work

### ISSUE THREAD

**Issue by novob** [Orainge/picgo-plugin-onemanager-orainge#1]

**Comment by ARRrui** [comment]
> 正是我想找的功能 感谢开发者 但是这个插件本身有个无法上传至vercel部署的Onemanager的问题 原作者暂时没空更新[laoxinH/picgo-plugin-onemanager#1](https://github.com/laoxinH/picgo-plugin-onemanager/issues/1) 请问是否有兴趣/精力完善下？感谢

啊我的issue好像提错地方了 我描述的是picgo插件的问题

**Comment by Orainge** [comment]
我自己的后端就是在 vercel 部署的，上传没有问题。后端用的是我修改过后的 onemanager 服务端 (https://github.com/Orainge/OneManager-php-orainge) ，部署教程同官方的版本。

**Comment by Orainge** [comment]
我自己的后端就是在 vercel 部署的，上传没有问题。后端用的是我修改过后的 onemanager 服务端 https://github.com/Orainge/OneManager-php-orainge ，部署教程同官方的版本。

如果想用原作者的插件，可以试下是否是这个原因导致上传不了。https://github.com/Orainge/picgo-plugin-onemanager/commit/97093e364aa0de2906366c2cd52fd6bcb573d23e

**Comment by ARRrui** [comment]
> 我自己的后端就是在 vercel 部署的，上传没有问题。后端用的是我修改过后的 onemanager 服务端 https://github.com/Orainge/OneManager-php-orainge ，部署教程同官方的版本。

上传成功了 看到平台变量里写“图床上传接口的 Token，设置后请求接口需要在 header 中填入 {auth: 此设置的值}，此处不设置值表示所有人都可以上传。” 我在picgo的框里把 {auth: }加上了 原来两个框填一样的就行了
